// Code generated by scripts/generate-models.go — do not edit manually.
// Run 'go generate ./...' to regenerate from the upstream model registry.
package wispai

var allModels = []Model{

	// ── OpenAI ────────────────────────────────────────────────────────────────

	{
		ID: "gpt-4o", Name: "GPT-4o", Provider: "openai",
		BaseURL:       "https://api.openai.com/v1",
		ContextWindow: 128_000, MaxTokens: 16_384,
		Cost: ModelCost{Input: 2.50, Output: 10.00},
	},
	{
		ID: "gpt-4o-mini", Name: "GPT-4o Mini", Provider: "openai",
		BaseURL:       "https://api.openai.com/v1",
		ContextWindow: 128_000, MaxTokens: 16_384,
		Cost: ModelCost{Input: 0.15, Output: 0.60},
	},
	{
		ID: "o4-mini", Name: "o4-mini", Provider: "openai",
		BaseURL:          "https://api.openai.com/v1",
		ContextWindow:    128_000, MaxTokens: 65_536,
		Cost:             ModelCost{Input: 1.10, Output: 4.40},
		SupportsThinking: true,
	},

	// ── DeepSeek ──────────────────────────────────────────────────────────────

	{
		ID: "deepseek-chat", Name: "DeepSeek V3", Provider: "deepseek",
		BaseURL:       "https://api.deepseek.com/v1",
		ContextWindow: 64_000, MaxTokens: 8_000,
		Cost: ModelCost{Input: 0.27, Output: 1.10},
	},
	{
		ID: "deepseek-reasoner", Name: "DeepSeek R1", Provider: "deepseek",
		BaseURL:          "https://api.deepseek.com/v1",
		ContextWindow:    64_000, MaxTokens: 8_000,
		Cost:             ModelCost{Input: 0.55, Output: 2.19},
		SupportsThinking: true,
	},

	// ── MiniMax ───────────────────────────────────────────────────────────────

	{
		ID: "MiniMax-Text-01", Name: "MiniMax Text-01", Provider: "minimax",
		BaseURL:       "https://api.minimaxi.chat/v1",
		ContextWindow: 1_000_000, MaxTokens: 4_096,
		Cost: ModelCost{Input: 0.80, Output: 3.50},
	},
	{
		ID: "MiniMax-M1", Name: "MiniMax M1", Provider: "minimax",
		BaseURL:          "https://api.minimaxi.chat/v1",
		ContextWindow:    1_000_000, MaxTokens: 40_960,
		Cost:             ModelCost{Input: 0.30, Output: 1.10},
		SupportsThinking: true,
	},

	// ── Groq ──────────────────────────────────────────────────────────────────

	{
		ID: "llama-3.3-70b-versatile", Name: "Llama 3.3 70B", Provider: "groq",
		BaseURL:       "https://api.groq.com/openai/v1",
		ContextWindow: 128_000, MaxTokens: 32_768,
		Cost: ModelCost{Input: 0.59, Output: 0.79},
	},
	{
		ID: "qwen-qwq-32b", Name: "Qwen QwQ 32B", Provider: "groq",
		BaseURL:          "https://api.groq.com/openai/v1",
		ContextWindow:    32_768, MaxTokens: 16_000,
		Cost:             ModelCost{Input: 0.29, Output: 0.39},
		SupportsThinking: true,
	},

	// ── xAI ───────────────────────────────────────────────────────────────────

	{
		ID: "grok-3", Name: "Grok 3", Provider: "xai",
		BaseURL:       "https://api.x.ai/v1",
		ContextWindow: 131_072, MaxTokens: 8_192,
		Cost: ModelCost{Input: 3.00, Output: 15.00},
	},
	{
		ID: "grok-3-mini", Name: "Grok 3 Mini", Provider: "xai",
		BaseURL:          "https://api.x.ai/v1",
		ContextWindow:    131_072, MaxTokens: 8_192,
		Cost:             ModelCost{Input: 0.30, Output: 0.50},
		SupportsThinking: true,
	},

	// ── Cerebras ──────────────────────────────────────────────────────────────

	{
		ID: "llama-4-scout-17b-16e-instruct", Name: "Llama 4 Scout", Provider: "cerebras",
		BaseURL:       "https://api.cerebras.ai/v1",
		ContextWindow: 131_072, MaxTokens: 16_384,
		Cost: ModelCost{Input: 0.10, Output: 0.10},
	},
}
